server:
  port: 8080

spring:
  application:
    name: SpringBoot-Security
  session:
    store-type: REDIS
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring-security?useUnicode=true&characterEncoding=utf8&serverTimezone=CTT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 5000

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

jwt:
  header: Authorization
  expire: 604800
  secret: aa6a857d5e0041bca69269cbc4bf0b86